import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` - see README
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'services/auth_service.dart';
import 'services/firestore_service.dart';
import 'services/presence_service.dart';
import 'services/theme_controller.dart';
import 'theme/app_theme.dart';

// Push notifications need the Blaze plan (see README) — once you upgrade,
// uncomment the NotificationService import/calls marked below to turn them on.
// import 'services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await ThemeController.instance.load();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeMode>(
      valueListenable: ThemeController.instance.mode,
      builder: (context, mode, _) {
        return MaterialApp(
          title: 'Chat App',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.light,
          darkTheme: AppTheme.dark,
          themeMode: mode,
          home: StreamBuilder(
            stream: AuthService().authStateChanges,
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const Scaffold(body: Center(child: CircularProgressIndicator()));
              }
              if (snapshot.hasData) {
                // NotificationService().init(snapshot.data!.uid); // uncomment once on Blaze
                return _PresenceGate(uid: snapshot.data!.uid, child: const HomeScreen());
              }
              return const LoginScreen();
            },
          ),
        );
      },
    );
  }
}

/// Starts/stops presence (online + last-seen) tracking around the logged-in
/// portion of the app.
class _PresenceGate extends StatefulWidget {
  final String uid;
  final Widget child;
  const _PresenceGate({required this.uid, required this.child});

  @override
  State<_PresenceGate> createState() => _PresenceGateState();
}

class _PresenceGateState extends State<_PresenceGate> {
  late final PresenceService _presence;

  @override
  void initState() {
    super.initState();
    _presence = PresenceService(FirestoreService());
    _presence.start(widget.uid);
  }

  @override
  void dispose() {
    _presence.stop();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}
